### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by keepithuman** [hogepodge/getting-started-with-openstack#1]
<img width="1174" alt="screen shot 2017-07-10 at 2 33 19 pm" src="https://user-images.githubusercontent.com/16569456/28033643-e2dea820-657c-11e7-9085-082c768ab04e.png">

**Comment by hogepodge** [comment]
Sometimes this happens. Unfortunately, the Puppet modules that are used to install OpenStack do not have a graceful failure mode. For some reason your VM lost network connectivity, or could not connect to the repository. The best thing to do is call `vagrant destroy` and start from scratch. Not the most satisfying answer in the world, but the only workaround I have for now. I occasionally run into the same problem, and I usually get the system up and running on the second try.

Thanks for the feedback.
